import { lazy } from 'react'

export const styles = [
  { id: 'glassmorphism', label: 'Glassmorphism', group: 'Modern', description: 'Frosted glass, translucent layers, depth through blur', descriptionZh: '毛玻璃效果，半透明层次，模糊深度', colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#0f3460', highlight: '#e94560' }, useCases: ['数据可视化', '创意展示', '品牌官网'], complexity: 4, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Inter', secondary: 'SF Pro' }, borderRadius: '16px', shadows: '多层模糊阴影', animations: '微妙悬浮', spacing: '8px基准', borderWidth: '1px半透明', darkMode: '原生支持', responsive: '优秀', performance: '中（backdrop-filter开销）', accessibility: '注意半透明层对比度' },
  { id: 'bento', label: 'Bento Grid', group: 'Modern', description: 'Modular asymmetric grid, spatial hierarchy', descriptionZh: '模块化非对称网格，空间层次', colors: { primary: '#0f0f0f', secondary: '#1a1a1a', accent: '#2d2d2d', highlight: '#6366f1' }, useCases: ['产品展示', '内容聚合', '个人主页'], complexity: 2, techDifficulty: 1, contrast: 'AAA', typography: { primary: 'SF Pro', secondary: 'Inter' }, borderRadius: '20px', shadows: '无阴影', animations: '网格重排', spacing: '12px基准', borderWidth: '无', darkMode: '原生暗色', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'neumorphism', label: 'Neumorphism', group: 'Modern', description: 'Soft UI, extruded elements, tactile depth', descriptionZh: '柔软UI，凸出元素，触感深度', colors: { primary: '#e0e5ec', secondary: '#d1d9e6', accent: '#c3cfe2', highlight: '#6d5dfc' }, useCases: ['控制面板', '智能家居', 'IoT设备'], complexity: 2, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Poppins', secondary: 'Roboto' }, borderRadius: '12px', shadows: '内外双层阴影', animations: '按压反馈', spacing: '16px基准', borderWidth: '无', darkMode: '需适配', responsive: '良好', performance: '中', accessibility: '对比度需注意' },
  { id: 'dark-premium', label: 'Dark Premium', group: 'Modern', description: 'Deep blacks, subtle accents, refined contrast', descriptionZh: '深黑底色，微妙点缀，精致对比', colors: { primary: '#0a0a0a', secondary: '#141414', accent: '#1f1f1f', highlight: '#c9a227' }, useCases: ['金融后台', '高端SaaS', '数据平台'], complexity: 2, techDifficulty: 1, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '8px', shadows: '微弱投影', animations: '克制过渡', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'gradient', label: 'Gradient Vibrant', group: 'Modern', description: 'Refined gradients, balanced color, dynamic energy', descriptionZh: '克制的渐变，平衡色彩，动态活力', colors: { primary: '#667eea', secondary: '#764ba2', accent: '#f093fb', highlight: '#f5576c' }, useCases: ['营销页面', '创意工具', '社交媒体'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Plus Jakarta Sans', secondary: 'Inter' }, borderRadius: '12px', shadows: '彩色光晕', animations: '渐变流动', spacing: '12px基准', borderWidth: '无', darkMode: '需适配', responsive: '良好', performance: '中', accessibility: '渐变文字需注意' },
  { id: 'minimal', label: 'Minimal Clean', group: 'Modern', description: 'Pure whitespace, restrained elegance, clarity', descriptionZh: '纯净留白，克制的优雅，最大化清晰', colors: { primary: '#ffffff', secondary: '#f8f9fa', accent: '#e9ecef', highlight: '#212529' }, useCases: ['文档工具', '笔记应用', '阅读平台'], complexity: 1, techDifficulty: 1, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'Georgia' }, borderRadius: '4px', shadows: '无', animations: '极简淡入', spacing: '24px基准', borderWidth: '1px', darkMode: '需反转', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'claymorphism', label: 'Claymorphism', group: 'Niche', description: '3D rounded cards, warm tones, friendly feel', descriptionZh: '3D圆角卡片，温暖色调，友好质感', colors: { primary: '#f5f0e8', secondary: '#e8e0d0', accent: '#d4c5a9', highlight: '#ff6b6b' }, useCases: ['教育平台', '儿童应用', '休闲游戏'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Nunito', secondary: 'Quicksand' }, borderRadius: '24px', shadows: '3D膨胀阴影', animations: '弹性回弹', spacing: '16px基准', borderWidth: '无', darkMode: '需适配', responsive: '良好', performance: '中', accessibility: '需注意' },
  { id: 'hud', label: 'HUD / Sci-Fi', group: 'Niche', description: 'Futuristic interface, monochrome cyan, technical', descriptionZh: '未来界面，单色青，技术美学', colors: { primary: '#0a0a0a', secondary: '#0d1117', accent: '#00d4ff', highlight: '#00ff88' }, useCases: ['监控系统', '游戏界面', '科技展示'], complexity: 4, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Orbitron', secondary: 'Share Tech Mono' }, borderRadius: '2px', shadows: '发光效果', animations: '扫描线/闪烁', spacing: '8px基准', borderWidth: '1px发光', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '发光效果需注意' },
  { id: 'swiss', label: 'Swiss Modern', group: 'Advanced', description: 'Strict grid, bold typography, information density', descriptionZh: '严格网格，粗体排版，高信息密度', colors: { primary: '#ffffff', secondary: '#f5f5f5', accent: '#000000', highlight: '#ff0000' }, useCases: ['新闻媒体', '数据报告', '学术平台'], complexity: 3, techDifficulty: 2, contrast: 'AAA', typography: { primary: 'Helvetica Neue', secondary: 'Akzidenz Grotesk' }, borderRadius: '0px', shadows: '无', animations: '网格切换', spacing: '8px基准', borderWidth: '无', darkMode: '需反转', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'spatial', label: 'Spatial UI', group: 'Advanced', description: 'Depth layers, floating elements, perspective', descriptionZh: '深度层次，浮动元素，透视效果', colors: { primary: '#000000', secondary: '#1a1a2e', accent: '#16213e', highlight: '#00d4ff' }, useCases: ['VR/AR界面', '3D展示', '空间计算'], complexity: 5, techDifficulty: 5, contrast: 'AA', typography: { primary: 'SF Pro', secondary: 'Inter' }, borderRadius: '16px', shadows: '3D透视阴影', animations: '空间变换', spacing: '12px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '低（3D渲染）', accessibility: '空间交互需注意' },
  { id: 'neubrutalism', label: 'Neubrutalism', group: 'Niche', description: 'Bold borders, solid shadows, high contrast', descriptionZh: '粗边框，实心阴影，高对比', colors: { primary: '#ffffff', secondary: '#ffd60a', accent: '#ff6b6b', highlight: '#4ecdc4' }, useCases: ['创意工作室', '时尚品牌', '艺术平台'], complexity: 2, techDifficulty: 1, contrast: 'AAA', typography: { primary: 'Space Grotesk', secondary: 'IBM Plex Mono' }, borderRadius: '0px', shadows: '4px硬阴影', animations: '生硬位移', spacing: '12px基准', borderWidth: '3px', darkMode: '需反转', responsive: '良好', performance: '高', accessibility: '优秀' },
  { id: 'sketch', label: 'Sketch', group: 'Niche', description: 'Hand-drawn feel, paper texture, approachable', descriptionZh: '手绘风格，纸张质感，平易近人', colors: { primary: '#faf8f5', secondary: '#f0ebe3', accent: '#e5ddd3', highlight: '#4a4a4a' }, useCases: ['设计工具', '创意笔记', '原型展示'], complexity: 3, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Caveat', secondary: 'Patrick Hand' }, borderRadius: '不规则', shadows: '手绘阴影', animations: '手绘擦除', spacing: '12px基准', borderWidth: '2px手绘', darkMode: '需适配', responsive: '中等', performance: '中', accessibility: '手写字体需注意' },
  { id: 'material3', label: 'Material 3', group: 'SaaS', description: 'Google M3 Expressive, rounded containers', descriptionZh: 'Google M3表达性设计，圆角容器', colors: { primary: '#6750a4', secondary: '#eaddff', accent: '#d0bcff', highlight: '#4f378b' }, useCases: ['Android应用', 'Google生态', '企业工具'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Roboto', secondary: 'Google Sans' }, borderRadius: '16px/28px', shadows: 'M3高程系统', animations: 'M3动效规范', spacing: '8dp基准', borderWidth: '无', darkMode: 'M3动态色彩', responsive: '优秀', performance: '高', accessibility: 'M3规范保障' },
  { id: 'stripe', label: 'Stripe Premium', group: 'SaaS', description: 'Industry benchmark, polished micro-interactions', descriptionZh: '行业标杆，精致的微交互', colors: { primary: '#0a2540', secondary: '#1a3a5c', accent: '#635bff', highlight: '#00d4aa' }, useCases: ['支付平台', '金融科技', '企业SaaS'], complexity: 4, techDifficulty: 3, contrast: 'AAA', typography: { primary: 'Söhne', secondary: 'SF Mono' }, borderRadius: '10px', shadows: '多层精致阴影', animations: '丰富微交互', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '优秀', performance: '中高', accessibility: '优秀' },
  { id: 'diffusion', label: 'Diffusion Light', group: 'Advanced', description: 'Soft scattered light, gentle glow, ethereal atmosphere', descriptionZh: '柔和弥散光，温润光晕，空灵氛围', colors: { primary: '#0a0a1a', secondary: '#1a1a3a', accent: '#2d2d5a', highlight: '#a78bfa' }, useCases: ['冥想应用', '高端展示', '艺术平台'], complexity: 4, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Inter', secondary: 'DM Sans' }, borderRadius: '20px', shadows: '弥散光晕', animations: '柔和呼吸', spacing: '12px基准', borderWidth: '1px半透明', darkMode: '原生暗色', responsive: '良好', performance: '中（多层光晕）', accessibility: '注意光晕对比度' },
  { id: 'skeuomorphism', label: 'Skeuomorphism', group: 'Modern', description: 'Realistic material textures, leather, metal, wood grain', descriptionZh: '经典拟物化，复刻现实材质肌理，皮革金属木纹', colors: { primary: '#2c2c3a', secondary: '#3a3a4a', accent: '#c9a84c', highlight: '#d4b65a' }, useCases: ['高端应用', '奢侈品展示', '经典风格'], complexity: 4, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Georgia', secondary: 'Palatino' }, borderRadius: '8px', shadows: '多层真实阴影', animations: '材质过渡', spacing: '12px基准', borderWidth: '1px金属描边', darkMode: '原生暗色', responsive: '良好', performance: '中', accessibility: '需注意纹理对比' },
  { id: 'neo-chinese', label: 'Neo-Chinese', group: 'Eastern', description: 'Ink wash, mortise lines, muted traditional palette', descriptionZh: '新中式UI，水墨留白，榫卯线条，青灰朱红低饱和国风配色', colors: { primary: '#f5f0e8', secondary: '#ebe5d9', accent: '#8b7355', highlight: '#b5544a' }, useCases: ['国风产品', '文化平台', '茶道/书法'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Noto Serif SC', secondary: 'Source Han Sans' }, borderRadius: '4px', shadows: '淡墨晕染', animations: '水墨晕开', spacing: '24px基准', borderWidth: '1px细线', darkMode: '需适配', responsive: '良好', performance: '高', accessibility: '需注意低饱和对比' },
  { id: 'guochao-retro', label: 'Guochao Retro', group: 'Eastern', description: 'Traditional patterns, bold colors, cloud/lattice motifs', descriptionZh: '国潮风UI，传统纹样，撞色排版，祥云窗棂元素', colors: { primary: '#1a0a0a', secondary: '#2a1010', accent: '#c41e3a', highlight: '#ffd700' }, useCases: ['国潮品牌', '文创产品', '传统节庆'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'ZCOOL KuaiLe', secondary: 'Noto Sans SC' }, borderRadius: '0px', shadows: '硬朗投影', animations: '传统纹样动画', spacing: '12px基准', borderWidth: '2px', darkMode: '原生暗色', responsive: '良好', performance: '高', accessibility: '需注意撞色对比' },
  { id: 'y2k', label: 'Y2K Millennium', group: 'Niche', description: 'High-sat laser, large rounded corners, jelly gradients', descriptionZh: 'Y2K千禧风，高饱和镭射，大圆角，果冻渐变', colors: { primary: '#0a0020', secondary: '#1a0040', accent: '#ff00ff', highlight: '#00ffff' }, useCases: ['潮流品牌', '音乐平台', 'Z世代产品'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Space Grotesk', secondary: 'Inter' }, borderRadius: '24px', shadows: '霓虹光晕', animations: '脉冲闪烁', spacing: '12px基准', borderWidth: '2px渐变', darkMode: '原生暗色', responsive: '良好', performance: '中', accessibility: '需注意霓虹对比' },
  { id: 'cream', label: 'Cream UI', group: 'Niche', description: 'Macaron pastels, extra rounded, soft matte, healing', descriptionZh: '奶油软萌风，马卡龙低饱和，超大圆角，治愈系', colors: { primary: '#faf5f0', secondary: '#f5ede4', accent: '#e8c8b0', highlight: '#d4a0a0' }, useCases: ['母婴产品', '治愈系应用', '轻量化工具'], complexity: 2, techDifficulty: 1, contrast: 'AA', typography: { primary: 'Quicksand', secondary: 'Nunito' }, borderRadius: '20px', shadows: '柔和投影', animations: '弹性回弹', spacing: '16px基准', borderWidth: '无', darkMode: '需适配', responsive: '优秀', performance: '高', accessibility: '需注意低饱和对比' },
  { id: 'jelly-glass', label: 'Jelly Glass', group: 'Niche', description: 'High-sat translucent soft glass, jelly wobble', descriptionZh: '果冻玻璃，高饱和半透软质玻璃，区别冷调毛玻璃', colors: { primary: '#ff6b9d', secondary: '#c44dff', accent: '#6e5cff', highlight: '#00d4ff' }, useCases: ['社交产品', '创意工具', '潮流应用'], complexity: 3, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Poppins', secondary: 'Inter' }, borderRadius: '24px', shadows: '彩色半透阴影', animations: '果冻晃动', spacing: '12px基准', borderWidth: '1px半透', darkMode: '需适配', responsive: '良好', performance: '中', accessibility: '需注意半透对比' },
  { id: 'pixel-art', label: 'Pixel Art', group: 'Niche', description: '8/16-bit retro pixel, game-oriented, nostalgic', descriptionZh: '像素风UI，8/16位复古像素，游戏向界面，怀旧质感', colors: { primary: '#1a1c2c', secondary: '#262b44', accent: '#ef7d57', highlight: '#a7f070' }, useCases: ['游戏界面', '复古产品', '极客社区'], complexity: 2, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Press Start 2P', secondary: 'VT323' }, borderRadius: '0px', shadows: '像素阴影', animations: '像素闪烁', spacing: '4px基准', borderWidth: '3px', darkMode: '原生暗色', responsive: '中等', performance: '高', accessibility: '像素字体需注意' },
  { id: 'cyberpunk', label: 'Cyberpunk', group: 'Niche', description: 'Neon clash, glitch offset, dark neon, dystopian tech', descriptionZh: '赛博朋克UI，霓虹撞色，故障错位，暗底霓虹', colors: { primary: '#0a0010', secondary: '#0f0018', accent: '#ff003c', highlight: '#00f0ff' }, useCases: ['游戏界面', '科技展示', '潮流品牌'], complexity: 4, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Orbitron', secondary: 'Share Tech Mono' }, borderRadius: '0px/斜切角', shadows: '霓虹发光', animations: '故障闪烁', spacing: '8px基准', borderWidth: '1px霓虹', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意霓虹对比' },
  { id: 'tech-minimal', label: 'Tech Minimal', group: 'SaaS', description: 'Cold gray monochrome, thin dividers, no decoration', descriptionZh: '科技极简，冷灰单色，细线条分割，政企科技产品专用', colors: { primary: '#fafafa', secondary: '#ffffff', accent: '#e5e5e5', highlight: '#171717' }, useCases: ['政企产品', '科技后台', 'B端系统'], complexity: 1, techDifficulty: 1, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'SF Mono' }, borderRadius: '0px', shadows: '无', animations: '无', spacing: '8px基准', borderWidth: '1px', darkMode: '需反转', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'matte-luxury', label: 'Matte Luxury', group: 'Advanced', description: 'Low-sat matte texture, fine metal outlines, no highlights', descriptionZh: '哑光轻奢，低饱和哑光肌理，细金属描边，无高光反光', colors: { primary: '#1a1816', secondary: '#1e1c1a', accent: '#8a7a5a', highlight: '#c8b898' }, useCases: ['高端品牌', '奢侈品官网', '私人银行'], complexity: 3, techDifficulty: 2, contrast: 'AA', typography: { primary: 'Cormorant Garamond', secondary: 'Inter' }, borderRadius: '2px', shadows: '微妙投影', animations: '克制过渡', spacing: '12px基准', borderWidth: '1px金属描边', darkMode: '原生暗色', responsive: '优秀', performance: '高', accessibility: '需注意低饱和对比' },
  { id: 'enterprise-minimal', label: 'Enterprise Minimal', group: 'SaaS', description: 'Pure B/W/gray, function-oriented, no decoration, government/large B2B', descriptionZh: '企业极简风，纯黑白灰功能导向，政务大型B端系统标配', colors: { primary: '#ffffff', secondary: '#fafafa', accent: '#e0e0e0', highlight: '#111111' }, useCases: ['政务系统', '大型B端', '企业后台'], complexity: 1, techDifficulty: 1, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'System UI' }, borderRadius: '0px', shadows: '无', animations: '无', spacing: '8px基准', borderWidth: '1px', darkMode: '需反转', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'dashboard-data', label: 'Dashboard Data', group: 'SaaS', description: 'Modular data layout, minimal charts, strong hierarchy, BI/back-office', descriptionZh: '数据仪表盘风，模块化数据布局，极简图表，BI后台专用', colors: { primary: '#0f1117', secondary: '#131620', accent: '#6366f1', highlight: '#22c55e' }, useCases: ['BI平台', '数据后台', '运维监控'], complexity: 3, techDifficulty: 2, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '6px', shadows: '微弱投影', animations: '数据刷新', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'magazine-layout', label: 'Magazine Layout', group: 'Advanced', description: 'Bold headline breaking grid, text-image interweaving, free layout', descriptionZh: '杂志版式UI，大标题破格排版，图文穿插，自由化版式', colors: { primary: '#faf8f5', secondary: '#ffffff', accent: '#1a1a1a', highlight: '#c4a35a' }, useCases: ['内容产品', '媒体平台', '博客杂志'], complexity: 3, techDifficulty: 2, contrast: 'AAA', typography: { primary: 'Georgia', secondary: 'Playfair Display' }, borderRadius: '0px', shadows: '无', animations: '版式切换', spacing: '24px基准', borderWidth: '无', darkMode: '需反转', responsive: '良好', performance: '高', accessibility: '优秀' },
  { id: 'boundless', label: 'Boundless UI', group: 'Advanced', description: 'No borders, no dividers, floating elements, extreme whitespace', descriptionZh: '无边界极简，无边框无分割线，全屏元素悬浮，极致留白', colors: { primary: '#ffffff', secondary: '#ffffff', accent: '#f0f0f0', highlight: '#000000' }, useCases: ['高端品牌', '极简产品', '禅意应用'], complexity: 2, techDifficulty: 2, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'SF Pro' }, borderRadius: '0px', shadows: '无', animations: '极简淡入', spacing: '32px基准', borderWidth: '无', darkMode: '需反转', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'topological-scientific', label: 'Topological Scientific', group: 'Scientific', description: 'Topological network visualization, node-edge graphs', descriptionZh: '拓扑科学可视化，节点-边关系网络图', colors: { primary: '#0a0e17', secondary: '#111827', accent: '#1e3a5f', highlight: '#00d4ff' }, useCases: ['科研平台', '网络分析', '生物信息'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'JetBrains Mono', secondary: 'Inter' }, borderRadius: '4px', shadows: '微弱投影', animations: '节点脉动', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'fluorescent-labeling', label: 'Fluorescent Labeling', group: 'Scientific', description: 'Fluorescent microscopy, labeled structures, dark field', descriptionZh: '荧光标记可视化，暗场荧光显微镜风格，标记结构高亮', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#00ff88' }, useCases: ['生物科研', '医学影像', '荧光分析'], complexity: 3, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Inter', secondary: 'SF Mono' }, borderRadius: '8px', shadows: '荧光光晕', animations: '荧光脉动', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '良好', performance: '中', accessibility: '需注意荧光对比' },
  { id: 'schematic-minimal', label: 'Schematic Minimal', group: 'Scientific', description: 'Clean schematic diagrams, thin lines, precise labels', descriptionZh: '示意图极简风，干净线条图，精确标注', colors: { primary: '#ffffff', secondary: '#f8f9fa', accent: '#e9ecef', highlight: '#2563eb' }, useCases: ['技术文档', '工程图纸', '教学材料'], complexity: 2, techDifficulty: 2, contrast: 'AAA', typography: { primary: 'Inter', secondary: 'Roboto Mono' }, borderRadius: '2px', shadows: '无', animations: '线条绘制', spacing: '8px基准', borderWidth: '1px', darkMode: '需反转', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'crystal-lattice', label: 'Crystal Lattice', group: 'Scientific', description: 'Crystal lattice structure, periodic arrangement, symmetry', descriptionZh: '晶格结构可视化，周期性排列，对称美感', colors: { primary: '#0a0a1a', secondary: '#0f0f2a', accent: '#1a1a4a', highlight: '#a78bfa' }, useCases: ['材料科学', '化学平台', '物理研究'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '晶格投影', animations: '晶格振动', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'dynamic-trajectory', label: 'Dynamic Trajectory', group: 'Scientific', description: 'Dynamic trajectories, motion paths, velocity vectors', descriptionZh: '动态轨迹可视化，运动路径，速度矢量', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#f97316' }, useCases: ['物理模拟', '运动分析', '机器人路径'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '轨迹残影', animations: '轨迹动画', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'microscopic-texture', label: 'Microscopic Texture', group: 'Scientific', description: 'Microscopic texture, surface analysis, material science', descriptionZh: '微观纹理可视化，表面分析，材料科学', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#22d3ee' }, useCases: ['材料科学', '表面工程', '纳米技术'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '微弱投影', animations: '纹理变化', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'academic-collage', label: 'Academic Collage', group: 'Scientific', description: 'Academic paper layout, multi-panel figures, citations', descriptionZh: '学术论文排版，多面板图表，引用标注', colors: { primary: '#ffffff', secondary: '#f8f9fa', accent: '#e9ecef', highlight: '#dc2626' }, useCases: ['学术论文', '研究报告', '文献管理'], complexity: 3, techDifficulty: 3, contrast: 'AAA', typography: { primary: 'Times New Roman', secondary: 'Computer Modern' }, borderRadius: '0px', shadows: '无', animations: '面板切换', spacing: '12px基准', borderWidth: '1px', darkMode: '需反转', responsive: '良好', performance: '高', accessibility: '优秀' },
  { id: 'cold-precision', label: 'Cold Precision', group: 'Scientific', description: 'Cold precision, clinical accuracy, sterile environment', descriptionZh: '冷峻精密风，临床精度，无菌环境', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#06b6d4' }, useCases: ['医疗设备', '精密仪器', '实验室管理'], complexity: 3, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '2px', shadows: '无', animations: '精确过渡', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '优秀', performance: '高', accessibility: '优秀' },
  { id: 'bionic-mechanism', label: 'Bionic Mechanism', group: 'Scientific', description: 'Bionic mechanism, biological structures, nature-inspired', descriptionZh: '仿生机构可视化，生物结构，自然启发设计', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#84cc16' }, useCases: ['仿生工程', '生物力学', '自然设计'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '8px', shadows: '有机投影', animations: '仿生运动', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'meteorological-contour', label: 'Meteorological Contour', group: 'Scientific', description: 'Weather contour maps, isobars, atmospheric data', descriptionZh: '气象等值线图，等压线，大气数据可视化', colors: { primary: '#0a0e17', secondary: '#111827', accent: '#1e3a5f', highlight: '#f59e0b' }, useCases: ['气象平台', '环境监测', '大气研究'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '微弱投影', animations: '等值线流动', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'satellite-cloud', label: 'Satellite Cloud', group: 'Scientific', description: 'Satellite imagery, cloud layer visualization, remote sensing', descriptionZh: '卫星云图可视化，云层渲染，遥感数据', colors: { primary: '#0a0e17', secondary: '#111827', accent: '#1e3a5f', highlight: '#38bdf8' }, useCases: ['卫星遥感', '气象预报', '地球科学'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '微弱投影', animations: '云层流动', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'heatmap-scientific', label: 'Heatmap Scientific', group: 'Scientific', description: 'Scientific heatmaps, thermal analysis, data density', descriptionZh: '科学热力图，热分析，数据密度可视化', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#ef4444' }, useCases: ['热力学', '基因表达', '数据密度'], complexity: 3, techDifficulty: 3, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '微弱投影', animations: '热力变化', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '良好', performance: '中', accessibility: '需注意' },
  { id: 'spectral-analysis', label: 'Spectral Analysis', group: 'Scientific', description: 'Spectral analysis, frequency domain, signal processing', descriptionZh: '光谱分析可视化，频域信号处理', colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#1a1a2e', highlight: '#a855f7' }, useCases: ['信号处理', '光谱分析', '声学研究'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '微弱投影', animations: '频谱动画', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
  { id: 'geological-map', label: 'Geological Map', group: 'Scientific', description: 'Geological mapping, strata visualization, earth science', descriptionZh: '地质图可视化，地层剖面，地球科学', colors: { primary: '#0a0e17', secondary: '#111827', accent: '#1e3a5f', highlight: '#d97706' }, useCases: ['地质勘探', '矿业平台', '地球科学'], complexity: 4, techDifficulty: 4, contrast: 'AA', typography: { primary: 'Inter', secondary: 'JetBrains Mono' }, borderRadius: '4px', shadows: '微弱投影', animations: '地层变化', spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色', responsive: '中等', performance: '中', accessibility: '需注意' },
]

export const groupedStyles = styles.reduce((acc, style) => {
  if (!acc[style.group]) acc[style.group] = []
  acc[style.group].push(style)
  return acc
}, {})

const dashboardModules = {
  glassmorphism: () => import('./dashboards/GlassmorphismDashboard'),
  bento: () => import('./dashboards/BentoDashboard'),
  neumorphism: () => import('./dashboards/NeumorphismDashboard'),
  'dark-premium': () => import('./dashboards/DarkPremiumDashboard'),
  gradient: () => import('./dashboards/GradientDashboard'),
  minimal: () => import('./dashboards/MinimalDashboard'),
  claymorphism: () => import('./dashboards/ClaymorphismDashboard'),
  hud: () => import('./dashboards/HUDDashboard'),
  swiss: () => import('./dashboards/SwissDashboard'),
  spatial: () => import('./dashboards/SpatialDashboard'),
  neubrutalism: () => import('./dashboards/NeubrutalismDashboard'),
  sketch: () => import('./dashboards/SketchDashboard'),
  material3: () => import('./dashboards/Material3Dashboard'),
  stripe: () => import('./dashboards/StripePremiumDashboard'),
  diffusion: () => import('./dashboards/DiffusionDashboard'),
  skeuomorphism: () => import('./dashboards/SkeuomorphismDashboard'),
  'neo-chinese': () => import('./dashboards/NeoChineseDashboard'),
  'guochao-retro': () => import('./dashboards/GuochaoRetroDashboard'),
  y2k: () => import('./dashboards/Y2KDashboard'),
  cream: () => import('./dashboards/CreamDashboard'),
  'jelly-glass': () => import('./dashboards/JellyGlassDashboard'),
  'pixel-art': () => import('./dashboards/PixelArtDashboard'),
  cyberpunk: () => import('./dashboards/CyberpunkDashboard'),
  'tech-minimal': () => import('./dashboards/TechMinimalDashboard'),
  'matte-luxury': () => import('./dashboards/MatteLuxuryDashboard'),
  'enterprise-minimal': () => import('./dashboards/EnterpriseMinimalDashboard'),
  'dashboard-data': () => import('./dashboards/DashboardDataDashboard'),
  'magazine-layout': () => import('./dashboards/MagazineLayoutDashboard'),
  boundless: () => import('./dashboards/BoundlessDashboard'),
  'topological-scientific': () => import('./dashboards/TopologicalScientificDashboard'),
  'fluorescent-labeling': () => import('./dashboards/FluorescentLabelingDashboard'),
  'schematic-minimal': () => import('./dashboards/SchematicMinimalDashboard'),
  'crystal-lattice': () => import('./dashboards/CrystalLatticeDashboard'),
  'dynamic-trajectory': () => import('./dashboards/DynamicTrajectoryDashboard'),
  'microscopic-texture': () => import('./dashboards/MicroscopicTextureDashboard'),
  'academic-collage': () => import('./dashboards/AcademicCollageDashboard'),
  'cold-precision': () => import('./dashboards/ColdPrecisionDashboard'),
  'bionic-mechanism': () => import('./dashboards/BionicMechanismDashboard'),
  'meteorological-contour': () => import('./dashboards/MeteorologicalContourDashboard'),
  'satellite-cloud': () => import('./dashboards/SatelliteCloudDashboard'),
  'heatmap-scientific': () => import('./dashboards/HeatmapScientificDashboard'),
  'spectral-analysis': () => import('./dashboards/SpectralAnalysisDashboard'),
  'geological-map': () => import('./dashboards/GeologicalMapDashboard'),
}

const dashboardComponentCache = {}

export function getDashboardComponent(id) {
  if (!dashboardComponentCache[id]) {
    const loader = dashboardModules[id]
    if (loader) {
      dashboardComponentCache[id] = lazy(loader)
    }
  }
  return dashboardComponentCache[id]
}

export function getPreviewComponent(id) {
  return getDashboardComponent(id)
}
