import { lazy } from 'react'

export const webPageGroups = {
  'Portfolio': { labelZh: '个人作品集', color: 'from-violet-500/20 to-indigo-500/20' },
  'Resume': { labelZh: '简历展示页', color: 'from-blue-500/20 to-cyan-500/20' },
  'Business Card': { labelZh: '个人名片网页', color: 'from-amber-500/20 to-yellow-500/20' },
  'Landing Page': { labelZh: '产品落地页', color: 'from-purple-500/20 to-pink-500/20' },
  'Official Homepage': { labelZh: '官网首页', color: 'from-indigo-500/20 to-blue-500/20' },
}

export const webPages = [
  {
    id: 'portfolio',
    label: 'Dark Premium',
    labelZh: '深色高端',
    group: 'Portfolio',
    description: 'Dark premium portfolio with project showcase, skills grid, and contact section',
    descriptionZh: '深色高端作品集，项目展示网格，技能可视化，联系模块',
    colors: { primary: '#0a0a0a', secondary: '#141414', accent: '#6366f1', highlight: '#a78bfa' },
    useCases: ['设计师作品集', '开发者主页', '创意人展示'],
    complexity: 3, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'JetBrains Mono' },
    borderRadius: '12px', shadows: '微妙投影', animations: '滚动渐入',
    spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'portfolio-light',
    label: 'Light Minimal',
    labelZh: '浅色极简',
    group: 'Portfolio',
    description: 'Light minimal portfolio with masonry grid, clean typography, and soft shadows',
    descriptionZh: '浅色极简作品集，瀑布流布局，清爽排版，柔和阴影',
    colors: { primary: '#fafafa', secondary: '#ffffff', accent: '#171717', highlight: '#6366f1' },
    useCases: ['摄影师主页', '设计师作品集', '艺术家展示'],
    complexity: 2, techDifficulty: 1, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'Georgia' },
    borderRadius: '8px', shadows: '柔和投影', animations: '淡入过渡',
    spacing: '16px基准', borderWidth: '1px', darkMode: '需反转',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'portfolio-bold',
    label: 'Bold Creative',
    labelZh: '大胆撞色',
    group: 'Portfolio',
    description: 'Bold colorful portfolio with striking contrasts, dynamic layouts, and vivid accents',
    descriptionZh: '大胆撞色作品集，强烈对比，动态布局，鲜明点缀',
    colors: { primary: '#0a0a0a', secondary: '#1a1a1a', accent: '#ff3366', highlight: '#00ff88' },
    useCases: ['创意工作室', '视觉设计师', '潮流品牌'],
    complexity: 4, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Space Grotesk', secondary: 'Inter' },
    borderRadius: '0px', shadows: '硬朗投影', animations: '弹跳动画',
    spacing: '8px基准', borderWidth: '2px', darkMode: '原生暗色',
    responsive: '良好', performance: '高', accessibility: '需注意',
  },
  {
    id: 'portfolio-bento',
    label: 'Bento Grid',
    labelZh: '便当盒网格',
    group: 'Portfolio',
    description: 'Apple-style bento grid portfolio with modular cards, soft colors, and clean hierarchy',
    descriptionZh: 'Apple风便当盒网格作品集，模块化卡片，柔和配色，清晰层级',
    colors: { primary: '#f5f5f7', secondary: '#ffffff', accent: '#0071e3', highlight: '#6366f1' },
    useCases: ['全栈开发者', '设计工程师', '产品设计师'],
    complexity: 3, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'SF Pro', secondary: 'Inter' },
    borderRadius: '16px', shadows: '柔和投影', animations: '弹性过渡',
    spacing: '12px基准', borderWidth: '1px', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'resume',
    label: 'Clean Professional',
    labelZh: '清爽专业',
    group: 'Resume',
    description: 'Clean professional resume with timeline, skills progress, and education section',
    descriptionZh: '专业简历页面，时间线经历，技能进度条，教育背景模块',
    colors: { primary: '#ffffff', secondary: '#f8fafc', accent: '#0f172a', highlight: '#3b82f6' },
    useCases: ['个人简历', '求职展示', '职业介绍'],
    complexity: 2, techDifficulty: 1, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'Georgia' },
    borderRadius: '8px', shadows: '卡片阴影', animations: '淡入过渡',
    spacing: '16px基准', borderWidth: '1px', darkMode: '需反转',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'resume-dark',
    label: 'Dark Modern',
    labelZh: '暗色现代',
    group: 'Resume',
    description: 'Dark modern resume with sidebar layout, glowing accents, and sleek typography',
    descriptionZh: '暗色现代简历，侧栏布局，发光点缀，流畅排版',
    colors: { primary: '#0a0a0a', secondary: '#141414', accent: '#22c55e', highlight: '#4ade80' },
    useCases: ['开发者简历', '技术求职', '极客展示'],
    complexity: 3, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'JetBrains Mono' },
    borderRadius: '12px', shadows: '微弱投影', animations: '滚动渐入',
    spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'resume-creative',
    label: 'Creative Timeline',
    labelZh: '创意时间线',
    group: 'Resume',
    description: 'Creative timeline-based resume with illustrated milestones and playful accents',
    descriptionZh: '创意时间线简历，插画里程碑，活泼点缀色',
    colors: { primary: '#fefce8', secondary: '#ffffff', accent: '#ca8a04', highlight: '#f59e0b' },
    useCases: ['创意行业简历', '设计师求职', '自由职业者'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Nunito', secondary: 'Inter' },
    borderRadius: '16px', shadows: '柔和投影', animations: '弹性动画',
    spacing: '12px基准', borderWidth: '1px', darkMode: '需适配',
    responsive: '良好', performance: '高', accessibility: '优秀',
  },
  {
    id: 'resume-swiss',
    label: 'Swiss International',
    labelZh: '瑞士国际主义',
    group: 'Resume',
    description: 'Swiss International style resume with strict grid, Helvetica typography, and objective layout',
    descriptionZh: '瑞士国际主义简历，严格网格，Helvetica排版，客观布局',
    colors: { primary: '#ffffff', secondary: '#f5f5f5', accent: '#e60000', highlight: '#000000' },
    useCases: ['设计从业者', '艺术指导', '品牌设计师'],
    complexity: 3, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'Helvetica Neue', secondary: 'Inter' },
    borderRadius: '2px', shadows: '无', animations: '无',
    spacing: '8px基准', borderWidth: '3px粗线', darkMode: '需适配',
    responsive: '优秀', performance: '极高', accessibility: '优秀',
  },

  {
    id: 'business-card',
    label: 'Dark Minimal',
    labelZh: '暗色极简',
    group: 'Business Card',
    description: 'Minimal centered card design with profile, social links, and subtle animations',
    descriptionZh: '极简居中名片设计，个人头像，社交链接，微妙动效',
    colors: { primary: '#0f0f0f', secondary: '#1a1a1a', accent: '#f59e0b', highlight: '#fbbf24' },
    useCases: ['个人名片', '社交主页', '链接聚合'],
    complexity: 1, techDifficulty: 1, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'SF Pro' },
    borderRadius: '16px', shadows: '光晕阴影', animations: '悬浮呼吸',
    spacing: '12px基准', borderWidth: '1px半透', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'business-card-gradient',
    label: 'Gradient Elegant',
    labelZh: '渐变优雅',
    group: 'Business Card',
    description: 'Elegant gradient card with smooth color transitions, refined typography, and soft glow',
    descriptionZh: '优雅渐变名片，平滑色彩过渡，精致排版，柔和光晕',
    colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#e94560', highlight: '#a78bfa' },
    useCases: ['品牌名片', '高端社交', '创意人主页'],
    complexity: 2, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Poppins', secondary: 'Inter' },
    borderRadius: '20px', shadows: '彩色光晕', animations: '渐变流动',
    spacing: '12px基准', borderWidth: '1px半透', darkMode: '原生暗色',
    responsive: '优秀', performance: '中', accessibility: '需注意',
  },
  {
    id: 'business-card-glass',
    label: 'Glassmorphism',
    labelZh: '毛玻璃',
    group: 'Business Card',
    description: 'Glassmorphism card with frosted backdrop blur, translucent layers, and floating elements',
    descriptionZh: '毛玻璃名片，背景模糊，半透明层次，浮动元素',
    colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#38bdf8', highlight: '#818cf8' },
    useCases: ['科技人名片', '设计师主页', '链接聚合页'],
    complexity: 2, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'SF Pro' },
    borderRadius: '24px', shadows: '模糊阴影', animations: '悬浮浮动',
    spacing: '12px基准', borderWidth: '1px半透', darkMode: '原生暗色',
    responsive: '优秀', performance: '中', accessibility: '需注意',
  },
  {
    id: 'business-card-neumorph',
    label: 'Neumorphism',
    labelZh: '新拟态',
    group: 'Business Card',
    description: 'Neumorphic card with soft extruded surfaces, subtle shadows, and tactile feel',
    descriptionZh: '新拟态名片，柔和凸起表面，微妙阴影，触感质感',
    colors: { primary: '#e0e5ec', secondary: '#d1d5db', accent: '#6366f1', highlight: '#8b95a5' },
    useCases: ['产品设计师', 'UI设计师', '软UI爱好者'],
    complexity: 2, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'SF Pro' },
    borderRadius: '20px', shadows: '双投影凸起', animations: '按压反馈',
    spacing: '12px基准', borderWidth: '无', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '需注意',
  },

  {
    id: 'landing-page',
    label: 'Dark SaaS',
    labelZh: '暗色SaaS',
    group: 'Landing Page',
    description: 'Conversion-focused product landing with hero, features, pricing, and testimonials',
    descriptionZh: '转化导向产品落地页，英雄区，功能特性，定价方案，用户评价',
    colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#8b5cf6', highlight: '#06b6d4' },
    useCases: ['SaaS产品', 'App推广', '营销活动'],
    complexity: 4, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'Plus Jakarta Sans' },
    borderRadius: '12px', shadows: '多层阴影', animations: '滚动动画',
    spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'landing-light',
    label: 'Light Startup',
    labelZh: '浅色创业',
    group: 'Landing Page',
    description: 'Light modern startup landing with clean hero, feature grid, and social proof',
    descriptionZh: '浅色现代创业落地页，清爽英雄区，功能网格，社会证明',
    colors: { primary: '#ffffff', secondary: '#f8fafc', accent: '#1e293b', highlight: '#6366f1' },
    useCases: ['创业产品', '工具推广', 'B端SaaS'],
    complexity: 3, techDifficulty: 1, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'Plus Jakarta Sans' },
    borderRadius: '12px', shadows: '柔和阴影', animations: '淡入过渡',
    spacing: '8px基准', borderWidth: '1px', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'landing-bold',
    label: 'Bold Gradient',
    labelZh: '大胆渐变',
    group: 'Landing Page',
    description: 'Bold gradient landing with vivid color transitions, dynamic sections, and energetic CTA',
    descriptionZh: '大胆渐变落地页，鲜明色彩过渡，动态区块，活力CTA',
    colors: { primary: '#0a0015', secondary: '#1a0030', accent: '#ff006e', highlight: '#8338ec' },
    useCases: ['潮流产品', 'Z世代应用', '创意工具'],
    complexity: 4, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Space Grotesk', secondary: 'Inter' },
    borderRadius: '16px', shadows: '彩色光晕', animations: '渐变流动',
    spacing: '8px基准', borderWidth: '1px半透', darkMode: '原生暗色',
    responsive: '良好', performance: '中', accessibility: '需注意',
  },
  {
    id: 'landing-bento',
    label: 'Bento Feature Grid',
    labelZh: '便当盒特性网格',
    group: 'Landing Page',
    description: 'Apple-style bento feature grid landing with modular cards, gradient icons, and clean pricing',
    descriptionZh: 'Apple风便当盒特性网格落地页，模块化卡片，渐变图标，清爽定价',
    colors: { primary: '#0a0a0a', secondary: '#111111', accent: '#8b5cf6', highlight: '#06b6d4' },
    useCases: ['API平台', '开发者工具', 'SaaS产品'],
    complexity: 4, techDifficulty: 3, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'SF Pro' },
    borderRadius: '16px', shadows: '柔和投影', animations: '悬停过渡',
    spacing: '12px基准', borderWidth: '1px半透', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'official-homepage',
    label: 'Light Corporate',
    labelZh: '浅色企业',
    group: 'Official Homepage',
    description: 'Corporate homepage with full hero section, stats, partners, and professional footer',
    descriptionZh: '企业官网首页，标配Hero大区，数据统计，合作伙伴，专业页脚',
    colors: { primary: '#ffffff', secondary: '#f1f5f9', accent: '#1e293b', highlight: '#6366f1' },
    useCases: ['企业官网', '品牌首页', '产品官网'],
    complexity: 4, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'Playfair Display' },
    borderRadius: '8px', shadows: '精致阴影', animations: '渐入动画',
    spacing: '8px基准', borderWidth: '1px', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'official-dark',
    label: 'Dark Tech',
    labelZh: '暗色科技',
    group: 'Official Homepage',
    description: 'Dark tech company homepage with futuristic hero, data visualization, and neon accents',
    descriptionZh: '暗色科技公司官网，未来感英雄区，数据可视化，霓虹点缀',
    colors: { primary: '#050505', secondary: '#0a0a0a', accent: '#00d4ff', highlight: '#6366f1' },
    useCases: ['科技公司官网', 'AI产品首页', '开发者平台'],
    complexity: 4, techDifficulty: 3, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'JetBrains Mono' },
    borderRadius: '8px', shadows: '发光阴影', animations: '扫描动画',
    spacing: '8px基准', borderWidth: '1px发光', darkMode: '原生暗色',
    responsive: '优秀', performance: '中', accessibility: '优秀',
  },
  {
    id: 'official-minimal',
    label: 'Zen Minimal',
    labelZh: '极简禅意',
    group: 'Official Homepage',
    description: 'Zen-inspired minimal homepage with generous whitespace, subtle typography, and calm palette',
    descriptionZh: '禅意极简官网，大量留白，含蓄排版，宁静配色',
    colors: { primary: '#faf8f5', secondary: '#ffffff', accent: '#8b7355', highlight: '#b5544a' },
    useCases: ['高端品牌官网', '文化机构', '设计工作室'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Noto Serif SC', secondary: 'Inter' },
    borderRadius: '4px', shadows: '无', animations: '极简淡入',
    spacing: '24px基准', borderWidth: '1px细线', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'official-magazine',
    label: 'Magazine Editorial',
    labelZh: '杂志编辑风',
    group: 'Official Homepage',
    description: 'Magazine editorial style homepage with large typography, editorial grid, and fashion-forward layout',
    descriptionZh: '杂志编辑风官网，大字排版，编辑网格，时尚前卫布局',
    colors: { primary: '#ffffff', secondary: '#fafafa', accent: '#000000', highlight: '#6b7280' },
    useCases: ['设计工作室', '时尚品牌', '文化机构'],
    complexity: 4, techDifficulty: 3, contrast: 'AAA',
    typography: { primary: 'Playfair Display', secondary: 'Inter' },
    borderRadius: '2px', shadows: '无', animations: '极简过渡',
    spacing: '32px基准', borderWidth: '1px', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'portfolio-glass',
    label: 'Glassmorphism',
    labelZh: '毛玻璃悬浮',
    group: 'Portfolio',
    description: 'Glassmorphism portfolio with frosted glass panels, translucent layers, and depth through blur',
    descriptionZh: '毛玻璃悬浮作品集，磨砂面板，半透明层次，模糊深度',
    colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#0f3460', highlight: '#e94560' },
    useCases: ['设计工程师', '创意开发者', '品牌设计师'],
    complexity: 4, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'SF Pro' },
    borderRadius: '16px', shadows: '多层模糊阴影', animations: '微妙悬浮',
    spacing: '8px基准', borderWidth: '1px半透明', darkMode: '原生暗色',
    responsive: '优秀', performance: '中', accessibility: '需注意半透明层对比度',
  },
  {
    id: 'portfolio-matte',
    label: 'Matte Luxury',
    labelZh: '哑光轻奢',
    group: 'Portfolio',
    description: 'Matte luxury portfolio with muted gold tones, refined typography, and understated elegance',
    descriptionZh: '哑光轻奢作品集，哑光金色调，精致排版，低调优雅',
    colors: { primary: '#1a1816', secondary: '#1e1c1a', accent: '#c8b898', highlight: '#8a7a5a' },
    useCases: ['奢侈品设计', '高端品牌', '艺术指导'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'Georgia' },
    borderRadius: '2px', shadows: '微妙投影', animations: '极简过渡',
    spacing: '16px基准', borderWidth: '1px细线', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'resume-neubrutal',
    label: 'Neubrutalism',
    labelZh: '新粗野主义',
    group: 'Resume',
    description: 'Neubrutalism resume with bold borders, solid shadows, high contrast, and raw energy',
    descriptionZh: '新粗野主义简历，粗边框，实心阴影，高对比，原始能量',
    colors: { primary: '#fff8e1', secondary: '#ffffff', accent: '#ff6b6b', highlight: '#ffd60a' },
    useCases: ['创意设计师', '独立开发者', '潮流从业者'],
    complexity: 2, techDifficulty: 1, contrast: 'AAA',
    typography: { primary: 'Space Grotesk', secondary: 'IBM Plex Mono' },
    borderRadius: '0px', shadows: '4px硬阴影', animations: '生硬位移',
    spacing: '12px基准', borderWidth: '3px', darkMode: '需反转',
    responsive: '良好', performance: '高', accessibility: '优秀',
  },
  {
    id: 'resume-cyberpunk',
    label: 'Cyberpunk',
    labelZh: '赛博朋克',
    group: 'Resume',
    description: 'Cyberpunk resume with neon clash, glitch offset, dark neon, and dystopian tech aesthetic',
    descriptionZh: '赛博朋克简历，霓虹撞色，故障错位，暗底霓虹，反乌托邦科技',
    colors: { primary: '#0a0010', secondary: '#0f0018', accent: '#ff003c', highlight: '#00f0ff' },
    useCases: ['游戏开发者', '安全工程师', '科技极客'],
    complexity: 4, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Orbitron', secondary: 'Share Tech Mono' },
    borderRadius: '0px/斜切角', shadows: '霓虹发光', animations: '故障闪烁',
    spacing: '8px基准', borderWidth: '1px霓虹', darkMode: '原生暗色',
    responsive: '中等', performance: '中', accessibility: '需注意霓虹对比',
  },

  {
    id: 'business-card-y2k',
    label: 'Y2K Millennium',
    labelZh: '千禧镭射',
    group: 'Business Card',
    description: 'Y2K millennium card with iridescent gradients, holographic effects, and retro-futuristic vibes',
    descriptionZh: '千禧镭射名片，彩虹渐变，全息效果，复古未来主义',
    colors: { primary: '#0a0020', secondary: '#120030', accent: '#ff00ff', highlight: '#00ffff' },
    useCases: ['潮流设计师', '音乐人', 'Z世代创作者'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'Space Grotesk' },
    borderRadius: '24px', shadows: '彩色光晕', animations: '镭射流动',
    spacing: '12px基准', borderWidth: '1px半透', darkMode: '原生暗色',
    responsive: '优秀', performance: '中', accessibility: '需注意',
  },
  {
    id: 'business-card-skeuomorph',
    label: 'Skeuomorphism',
    labelZh: '拟物化',
    group: 'Business Card',
    description: 'Skeuomorphic card with realistic textures, depth shadows, and tactile material feel',
    descriptionZh: '拟物化名片，真实纹理，深度阴影，触感材质',
    colors: { primary: '#2c2c3a', secondary: '#3a3a4a', accent: '#c9a84c', highlight: '#8a7a5a' },
    useCases: ['传统工艺师', '高端定制', '奢侈品从业者'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Georgia', secondary: 'Inter' },
    borderRadius: '12px', shadows: '多层真实阴影', animations: '按压反馈',
    spacing: '12px基准', borderWidth: '1px金属', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'landing-stripe',
    label: 'Stripe Premium',
    labelZh: '行业标杆',
    group: 'Landing Page',
    description: 'Stripe-inspired premium landing with deep navy, purple accents, code examples, and enterprise trust',
    descriptionZh: 'Stripe风格行业标杆落地页，深海军蓝，紫色点缀，代码示例，企业信任',
    colors: { primary: '#0a2540', secondary: '#0d2d4a', accent: '#635bff', highlight: '#00d4aa' },
    useCases: ['支付平台', 'API产品', '企业SaaS'],
    complexity: 4, techDifficulty: 3, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'JetBrains Mono' },
    borderRadius: '12px', shadows: '精致阴影', animations: '渐入动画',
    spacing: '8px基准', borderWidth: '1px', darkMode: '原生暗色',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'landing-clay',
    label: 'Claymorphism',
    labelZh: '黏土风',
    group: 'Landing Page',
    description: 'Claymorphism landing with soft inflated shapes, inner shadows, and playful tactile feel',
    descriptionZh: '黏土风落地页，柔和膨胀形状，内阴影，趣味触感',
    colors: { primary: '#f5f0e8', secondary: '#ebe5d9', accent: '#ff6b6b', highlight: '#4ecdc4' },
    useCases: ['教育产品', '儿童应用', '趣味工具'],
    complexity: 2, techDifficulty: 2, contrast: 'AAA',
    typography: { primary: 'Nunito', secondary: 'Inter' },
    borderRadius: '24px', shadows: '内外双阴影', animations: '弹性动画',
    spacing: '12px基准', borderWidth: '无', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'official-neochinese',
    label: 'Neo-Chinese',
    labelZh: '新中式',
    group: 'Official Homepage',
    description: 'Neo-Chinese homepage blending traditional aesthetics with modern design, ink wash, and restrained elegance',
    descriptionZh: '新中式官网，传统美学与现代设计融合，水墨意境，含蓄雅致',
    colors: { primary: '#f5f0e8', secondary: '#ebe5d9', accent: '#8b7355', highlight: '#b5544a' },
    useCases: ['文化品牌', '茶道工坊', '东方美学'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Noto Serif SC', secondary: 'Inter' },
    borderRadius: '2px', shadows: '微妙投影', animations: '极简淡入',
    spacing: '24px基准', borderWidth: '1px细线', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },
  {
    id: 'official-boundless',
    label: 'Boundless UI',
    labelZh: '无边界极简',
    group: 'Official Homepage',
    description: 'Boundless minimal homepage with extreme whitespace, ultra-clean typography, and nothing-to-hide philosophy',
    descriptionZh: '无边界极简官网，极致留白，超清爽排版，坦诚哲学',
    colors: { primary: '#ffffff', secondary: '#f5f5f5', accent: '#000000', highlight: '#cccccc' },
    useCases: ['极简品牌', '设计工作室', '建筑事务所'],
    complexity: 2, techDifficulty: 1, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'Helvetica Neue' },
    borderRadius: '0px', shadows: '无', animations: '无',
    spacing: '32px基准', borderWidth: '1px细线', darkMode: '需适配',
    responsive: '优秀', performance: '极高', accessibility: '优秀',
  },

  {
    id: 'portfolio-sketch',
    label: 'Sketch',
    labelZh: '手绘风格',
    group: 'Portfolio',
    description: 'Hand-drawn feel portfolio with paper texture, dashed borders, and approachable warmth',
    descriptionZh: '手绘风格作品集，纸张质感，虚线边框，平易近人的温暖',
    colors: { primary: '#faf8f5', secondary: '#f0ebe3', accent: '#8b7355', highlight: '#4a4a4a' },
    useCases: ['插画师作品集', '创意笔记', '手工艺人'],
    complexity: 3, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Georgia', secondary: 'Caveat' },
    borderRadius: '不规则', shadows: '手绘阴影', animations: '手绘擦除',
    spacing: '12px基准', borderWidth: '2px虚线', darkMode: '需适配',
    responsive: '中等', performance: '中', accessibility: '手写字体需注意',
  },

  {
    id: 'resume-material3',
    label: 'Material 3',
    labelZh: 'M3表达性',
    group: 'Resume',
    description: 'Google Material 3 Expressive resume with rounded containers, dynamic color, and M3 motion',
    descriptionZh: 'Google M3表达性简历，圆角容器，动态色彩，M3动效规范',
    colors: { primary: '#fffbfe', secondary: '#f7f2fa', accent: '#6750a4', highlight: '#e8def8' },
    useCases: ['Android开发者', 'Google生态', '设计系统'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Roboto', secondary: 'Google Sans' },
    borderRadius: '16px/28px', shadows: 'M3高程系统', animations: 'M3动效规范',
    spacing: '8dp基准', borderWidth: '无', darkMode: 'M3动态色彩',
    responsive: '优秀', performance: '高', accessibility: 'M3规范保障',
  },

  {
    id: 'business-card-jelly',
    label: 'Jelly Glass',
    labelZh: '果冻玻璃',
    group: 'Business Card',
    description: 'High-sat translucent soft glass with jelly wobble, colorful gradients, and warm glow',
    descriptionZh: '果冻玻璃名片，高饱和半透软质，彩色渐变，温暖光晕',
    colors: { primary: '#ff6b9d', secondary: '#c44dff', accent: '#6e5cff', highlight: '#00d4ff' },
    useCases: ['社交产品', '创意工具', '潮流应用'],
    complexity: 3, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Poppins', secondary: 'Inter' },
    borderRadius: '24px', shadows: '彩色半透阴影', animations: '果冻晃动',
    spacing: '12px基准', borderWidth: '1px半透', darkMode: '需适配',
    responsive: '良好', performance: '中', accessibility: '需注意半透对比',
  },

  {
    id: 'landing-spatial',
    label: 'Spatial UI',
    labelZh: '空间UI',
    group: 'Landing Page',
    description: 'Spatial computing landing with depth layers, floating elements, perspective, and 3D depth',
    descriptionZh: '空间计算落地页，深度层次，浮动元素，透视效果，3D深度',
    colors: { primary: '#000000', secondary: '#0a0a0a', accent: '#00d4ff', highlight: '#6e5cff' },
    useCases: ['VR/AR平台', '空间计算', '3D展示'],
    complexity: 5, techDifficulty: 5, contrast: 'AA',
    typography: { primary: 'SF Pro', secondary: 'Inter' },
    borderRadius: '16px', shadows: '3D透视阴影', animations: '空间变换',
    spacing: '12px基准', borderWidth: '1px', darkMode: '原生暗色',
    responsive: '中等', performance: '中', accessibility: '空间交互需注意',
  },

  {
    id: 'official-hud',
    label: 'HUD / Sci-Fi',
    labelZh: '科幻HUD',
    group: 'Official Homepage',
    description: 'Futuristic HUD homepage with monochrome cyan, scan lines, glowing borders, and technical aesthetic',
    descriptionZh: '科幻HUD官网，单色青，扫描线，发光边框，技术美学',
    colors: { primary: '#0a0a0a', secondary: '#0d1117', accent: '#00d4ff', highlight: '#00ff88' },
    useCases: ['科技公司官网', '安全平台', 'AI产品'],
    complexity: 4, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Orbitron', secondary: 'Share Tech Mono' },
    borderRadius: '2px', shadows: '发光效果', animations: '扫描线/闪烁',
    spacing: '8px基准', borderWidth: '1px发光', darkMode: '原生暗色',
    responsive: '中等', performance: '中', accessibility: '发光效果需注意',
  },

  {
    id: 'portfolio-pixel',
    label: 'Pixel Art',
    labelZh: '像素风',
    group: 'Portfolio',
    description: '8/16-bit retro pixel portfolio with game-oriented interface and nostalgic charm',
    descriptionZh: '像素风作品集，8/16位复古像素，游戏向界面，怀旧质感',
    colors: { primary: '#1a1c2c', secondary: '#262b44', accent: '#ef7d57', highlight: '#a7f070' },
    useCases: ['游戏开发者', '像素艺术家', '极客社区'],
    complexity: 2, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'Press Start 2P', secondary: 'VT323' },
    borderRadius: '0px', shadows: '像素阴影', animations: '像素闪烁',
    spacing: '4px基准', borderWidth: '3px', darkMode: '原生暗色',
    responsive: '中等', performance: '高', accessibility: '像素字体需注意',
  },

  {
    id: 'resume-tech-minimal',
    label: 'Tech Minimal',
    labelZh: '科技极简',
    group: 'Resume',
    description: 'Cold gray monochrome resume with thin dividers, no decoration, and function-first approach',
    descriptionZh: '科技极简简历，冷灰单色，细线分割，功能导向',
    colors: { primary: '#fafafa', secondary: '#ffffff', accent: '#e5e5e5', highlight: '#171717' },
    useCases: ['工程师简历', '政企求职', 'B端从业者'],
    complexity: 1, techDifficulty: 1, contrast: 'AAA',
    typography: { primary: 'Inter', secondary: 'SF Mono' },
    borderRadius: '0px', shadows: '无', animations: '无',
    spacing: '8px基准', borderWidth: '1px', darkMode: '需反转',
    responsive: '优秀', performance: '高', accessibility: '优秀',
  },

  {
    id: 'business-card-cream',
    label: 'Cream UI',
    labelZh: '奶油软萌',
    group: 'Business Card',
    description: 'Macaron pastels card with extra rounded corners, soft matte, and healing warmth',
    descriptionZh: '奶油软萌名片，马卡龙低饱和，超大圆角，治愈系',
    colors: { primary: '#faf5f0', secondary: '#f5ede4', accent: '#e8c8b0', highlight: '#d4a0a0' },
    useCases: ['母婴产品', '治愈系应用', '轻量化工具'],
    complexity: 2, techDifficulty: 1, contrast: 'AA',
    typography: { primary: 'Quicksand', secondary: 'Nunito' },
    borderRadius: '20px', shadows: '柔和投影', animations: '弹性回弹',
    spacing: '16px基准', borderWidth: '无', darkMode: '需适配',
    responsive: '优秀', performance: '高', accessibility: '需注意低饱和对比',
  },

  {
    id: 'landing-diffusion',
    label: 'Diffusion Light',
    labelZh: '弥散光',
    group: 'Landing Page',
    description: 'Soft scattered light landing with gentle glow, ethereal atmosphere, and luminous depth',
    descriptionZh: '弥散光落地页，柔和光晕，空灵氛围，温润深度',
    colors: { primary: '#0a0a1a', secondary: '#1a1a3a', accent: '#2d2d5a', highlight: '#a78bfa' },
    useCases: ['冥想应用', '高端展示', '艺术平台'],
    complexity: 4, techDifficulty: 3, contrast: 'AA',
    typography: { primary: 'Inter', secondary: 'DM Sans' },
    borderRadius: '20px', shadows: '弥散光晕', animations: '柔和呼吸',
    spacing: '12px基准', borderWidth: '1px半透明', darkMode: '原生暗色',
    responsive: '良好', performance: '中', accessibility: '注意光晕对比度',
  },

  {
    id: 'official-guochao',
    label: 'Guochao Retro',
    labelZh: '国潮风',
    group: 'Official Homepage',
    description: 'Guochao retro homepage with traditional patterns, bold colors, and cloud/lattice motifs',
    descriptionZh: '国潮风官网，传统纹样，撞色排版，祥云窗棂元素',
    colors: { primary: '#1a0a0a', secondary: '#2a1010', accent: '#c41e3a', highlight: '#ffd700' },
    useCases: ['国潮品牌', '文创产品', '传统节庆'],
    complexity: 3, techDifficulty: 2, contrast: 'AA',
    typography: { primary: 'ZCOOL KuaiLe', secondary: 'Noto Sans SC' },
    borderRadius: '0px', shadows: '硬朗投影', animations: '传统纹样动画',
    spacing: '12px基准', borderWidth: '2px', darkMode: '原生暗色',
    responsive: '良好', performance: '高', accessibility: '需注意撞色对比',
  },
]

export const groupedWebPages = webPages.reduce((acc, page) => {
  if (!acc[page.group]) acc[page.group] = []
  acc[page.group].push(page)
  return acc
}, {})

const webPageModules = {
  'portfolio': () => import('./webpages/PortfolioPage'),
  'portfolio-light': () => import('./webpages/PortfolioLightPage'),
  'portfolio-bold': () => import('./webpages/PortfolioBoldPage'),
  'portfolio-bento': () => import('./webpages/PortfolioBentoPage'),
  'resume': () => import('./webpages/ResumePage'),
  'resume-dark': () => import('./webpages/ResumeDarkPage'),
  'resume-creative': () => import('./webpages/ResumeCreativePage'),
  'resume-swiss': () => import('./webpages/ResumeSwissPage'),
  'business-card': () => import('./webpages/BusinessCardPage'),
  'business-card-gradient': () => import('./webpages/BusinessCardGradientPage'),
  'business-card-glass': () => import('./webpages/BusinessCardGlassPage'),
  'business-card-neumorph': () => import('./webpages/BusinessCardNeumorphPage'),
  'landing-page': () => import('./webpages/LandingPage'),
  'landing-light': () => import('./webpages/LandingLightPage'),
  'landing-bold': () => import('./webpages/LandingBoldPage'),
  'landing-bento': () => import('./webpages/LandingBentoPage'),
  'official-homepage': () => import('./webpages/OfficialHomepage'),
  'official-dark': () => import('./webpages/OfficialDarkPage'),
  'official-minimal': () => import('./webpages/OfficialMinimalPage'),
  'official-magazine': () => import('./webpages/OfficialMagazinePage'),
  'portfolio-glass': () => import('./webpages/PortfolioGlassPage'),
  'portfolio-matte': () => import('./webpages/PortfolioMattePage'),
  'resume-neubrutal': () => import('./webpages/ResumeNeubrutalPage'),
  'resume-cyberpunk': () => import('./webpages/ResumeCyberpunkPage'),
  'business-card-y2k': () => import('./webpages/BusinessCardY2KPage'),
  'business-card-skeuomorph': () => import('./webpages/BusinessCardSkeuomorphPage'),
  'landing-stripe': () => import('./webpages/LandingStripePage'),
  'landing-clay': () => import('./webpages/LandingClayPage'),
  'official-neochinese': () => import('./webpages/OfficialNeoChinesePage'),
  'official-boundless': () => import('./webpages/OfficialBoundlessPage'),
  'portfolio-sketch': () => import('./webpages/PortfolioSketchPage'),
  'resume-material3': () => import('./webpages/ResumeMaterial3Page'),
  'business-card-jelly': () => import('./webpages/BusinessCardJellyGlassPage'),
  'landing-spatial': () => import('./webpages/LandingSpatialPage'),
  'official-hud': () => import('./webpages/OfficialHUDPage'),
  'portfolio-pixel': () => import('./webpages/PortfolioPixelPage'),
  'resume-tech-minimal': () => import('./webpages/ResumeTechMinimalPage'),
  'business-card-cream': () => import('./webpages/BusinessCardCreamPage'),
  'landing-diffusion': () => import('./webpages/LandingDiffusionPage'),
  'official-guochao': () => import('./webpages/OfficialGuochaoPage'),
}

const webPageComponentCache = {}

export function getWebPageComponent(id) {
  if (!webPageComponentCache[id]) {
    const loader = webPageModules[id]
    if (loader) {
      webPageComponentCache[id] = lazy(loader)
    }
  }
  return webPageComponentCache[id]
}
